# Generated by Django 4.2.5 on 2023-09-26 07:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app2', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='registertable',
        ),
    ]
