# Generated by Django 4.2.5 on 2023-10-05 18:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_alter_userorder_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userorder',
            name='book_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
